added black duck policy for cluster management
open-cluster-management-io/policy-collection pull request #103
Opened 2021-03-31 19:27 UTC by gautambaghel

@ycao56 - Please double check this PR

2021-03-31 19:50 UTC, dhaiducek commented
@gautambaghel We've updated the primary branch. Would you please edit this PR to change the base branch from `master` to `main`? Thanks!

2021-03-31 19:54 UTC, gautambaghel commented
@dhaiducek -Done!

2021-03-31 20:06 UTC, ycao56 commented on community/SI-System-and-Information-Integrity/policy-blackduck.yaml
> +  namespace: default
remove hard coded namespace for policy

2021-03-31 20:07 UTC, ycao56 commented on community/SI-System-and-Information-Integrity/policy-blackduck.yaml
> +  namespace: default
remove hard coded namespace for policy

2021-03-31 20:07 UTC, ycao56 commented on community/SI-System-and-Information-Integrity/policy-blackduck.yaml
> +  namespace: default
remove hard coded namespace for policy

2021-03-31 20:08 UTC, ycao56 commented
@gautambaghel please add this policy to https://github.com/open-cluster-management/policy-collection/blob/main/community/README.md
It's also nice to have some descriptions to explain what policy does in policy-blackduck.yaml file itself.

2021-04-01 22:30 UTC, gautambaghel commented
@ycao56 - made requested changes, pls verify. thanks!

2021-04-02 00:25 UTC, ycao56 requested changes

2021-04-02 00:25 UTC, ycao56 commented on community/README.md
> +- [Policies -- Community](#policies----community)
These seems to be unexpected change. Can you revert? Others look fine to me

2021-04-06 15:11 UTC, gautambaghel commented on community/README.md
> +- [Policies -- Community](#policies----community)
@ycao56 -- Visual studio automatically fixed the table of contents, this looks correct to me. The table of content was inaccurate previously.

If you'd still like me to revert it, I can. Thanks

2021-04-06 16:48 UTC, ycao56 commented on community/README.md
> +- [Policies -- Community](#policies----community)
@gautambaghel please revert. Thanks.

2021-04-06 16:55 UTC, ycao56 approved these changes

2021-04-06 16:55 UTC, merged