add policy consumer instructions and change catalogs to tables
open-cluster-management-io/policy-collection pull request #13
Opened 2020-08-06 16:44 UTC by willkutler

https://github.com/open-cluster-management/backlog/issues/4000

2020-08-06 17:13 UTC, ycao56 commented on community/README.md
> +## Deploying community policies to your cluster
move this after ### Custom policy controllers

2020-08-06 17:15 UTC, ycao56 commented on community/README.md
> +Some policy consumers are stored as images on the Operator hub. These consumers can simply be deployed by creating a Policy with child [Configuration Policies](https://github.com/open-cluster-managem
Some policy consumers are packaged as [operators](https://coreos.com/operators/) and are available on the [Operator hub](https://operatorhub.io/)

2020-08-06 19:05 UTC, ycao56 approved these changes

2020-08-06 19:46 UTC, dockerymick requested changes

2020-08-06 19:46 UTC, dockerymick commented on community/README.md
> +    <td><a href="./CM-Configuration-Management/policy-trusted-node.yaml">Trusted Node policy</a>: Use the trusted node policy to detect if there are untrusted/unattested nodes in the cluster.</td>
Remove the slash (\) and use or, for example: Use the trusted node policy to detect if there are untrusted or unattested nodes in the cluster.

2020-08-06 19:46 UTC, dockerymick commented on community/README.md
> +    <td><a href="./CM-Configuration-Management/policy-opa-sample.yaml">OPA Sample policy</a>: Use the Open Policy Agent (OPA) Sample policy to view example of how an OPA policy can be <br>created usi
Sample policy to view an example

2020-08-06 19:46 UTC, dockerymick commented on community/README.md
> +    <td>See the <a href="https://github.com/ycao56/mcm-opa">OPA example repository</a>. Note: OPA must be installed to use the OPA ConfigMap policy.</td>
Add 4 asterisks surrounding the word Note to bold the word.

`**Note**`

2020-08-06 19:46 UTC, dockerymick commented on community/README.md
> +    <td><a href="./SI-System-and-Information-Integrity/policy-falco.yaml">Falco Cloud-Native runtime security</a> -- Falco parses Linux system calls from the kernel at runtime, and asserts <br>the st
Update: Falco Cloud-Native runtime security--

TO 

Falco Cloud-Native runtime security:

2020-08-06 19:46 UTC, dockerymick commented on community/README.md
> +    <td><a href="./SI-System-and-Information-Integrity/policy-sysdig.yaml">Sysdig Agent</a> -- Enforce Sysdig Agent deployment in all targeted clusters. The Sysdig Secure DevOps Platform <br> converg
Update: Sysdig Agent--

TO 

Sysdig Agent:

The Sysdig Secure DevOps Platform converges security and compliance with performance and capacity monitoring, to create a secure DevOps workflow.

2020-08-06 19:46 UTC, dockerymick commented on community/README.md
> +While the policies in [stable](../stable) all have out-of-the-box support installed with RHACM, community policies are maintained by the open source community, and thus you may need to deploy extra p
While the policies in [stable](../stable) all have out-of-the-box support installed with RHACM, community policies are maintained by the open source community. You might need to deploy extra policy consumers in order for community policies to work as intended.

2020-08-06 19:46 UTC, dockerymick commented on community/README.md
> +While the policies in [stable](../stable) all have out-of-the-box support installed with RHACM, community policies are maintained by the open source community, and thus you may need to deploy extra p
close the code after `<version>"`

also change "you will need to deploy" to "upi must deploy the CustomResourceDefiniton (CRD) for the policy before you create it.

2020-08-06 19:46 UTC, dockerymick commented on community/README.md
> +While the policies in [stable](../stable) all have out-of-the-box support installed with RHACM, community policies are maintained by the open source community, and thus you may need to deploy extra p
Change "you will need to deploy the corresponding policy consumers to handle them." 

TO 

"you must deploy the corresponding policy consumers to handle them."

2020-08-06 19:46 UTC, dockerymick commented on community/README.md
> +- Run `kubectl apply -f <CRD path>` on your cluster to install the CRD for the custom policy.
Run the following command on your cluster to install the CRD for the custom policy: `kubectl apply -f <CRD path>`

2020-08-06 19:46 UTC, dockerymick commented on community/README.md
> +- Run `kubectl apply -f deploy/` to set up the operator and service account that will run the controller on your cluster.
Run the following command  to set up the operator and service account that runs the controller on your cluster: `kubectl apply -f deploy/`

2020-08-06 19:46 UTC, dockerymick commented on community/README.md
> +Some policy consumers are packaged as [operators](https://coreos.com/operators/) and are available on the [Operator hub](https://operatorhub.io/). These consumers can simply be deployed by creating a
change Policy to policy and Configuration Policies to configuration policies

The following tasks are complete when you apply configuration policies: 

- Create a namespace to deploy the operator on, if necessary

Please capitalize the beginning of the statement (in bullet points)

2020-08-06 19:46 UTC, dockerymick commented on community/README.md
> +Occasionally, policies in this folder may be consumed by controllers that do not fall into either of the two categories above. To get the most out of these policies, consult the "prerequisites" secti
Occasionally, policies in this folder might be consumed by controllers that do not fall into either of the two categories previously mentioned.

2020-08-07 15:43 UTC, dockerymick requested changes

2020-08-07 15:43 UTC, dockerymick commented on community/README.md
> +Some policy consumers are packaged as [operators](https://coreos.com/operators/) and are available on the [Operator hub](https://operatorhub.io/). These consumers can simply be deployed by creating a
Update "These configuration policies may include:" TO "The configuration policies might include the following information:"

Let's remove the verbs in the bullet point bc we are listing what is included in the policy vs. stating what the policy does when it is applied. Therefore, i suggest the following changes: 

"The configuration policies might include the following information:

* A namespace to deploy...
* ClusterServiceVersion with install...
* An OperatorGroup
* A Subscription
* The custom resource defined by the consumer..."

2020-08-07 15:43 UTC, dockerymick commented on community/README.md
> +Occasionally, policies in this folder might be consumed by controllers that do not fall into either of the two categories previously mentioned. To get the most out of these policies, consult the "pre
Update "To get the most out of these policies, consult the "prerequisites" section in the catalog above."

TO 

"To get the most out of these policies, see the `[Security control catalog](#security-control-catalog)`.


For clarification, the link should not be in codeblock. I used them so that you can see how to link the section. I will check it again after you make the changes

2020-08-07 16:23 UTC, dockerymick approved these changes
looks good!

2020-08-07 16:27 UTC, merged