added policies
open-cluster-management-io/policy-collection pull request #134
Opened 2021-07-22 08:07 UTC by ch-stark

Signed-off-by: Christian Stark <cstark@cstark.muc.csb>

2021-07-27 02:51 UTC, ch-stark commented
please delay with review as I plan to add more

2021-07-29 12:59 UTC, gparvin commented
/hold

2021-08-03 07:20 UTC, vbnrh requested changes

2021-08-03 07:20 UTC, vbnrh commented on community/CM-Configuration-Management/policy-ocs-setup.yaml
> +    - objectDefinition:
can we add the below configuration ? This operator only functions in this namespace
```
- objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-ocs-namespace
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-storage
          remediationAction: inform
          severity: high
          
```

2021-08-19 10:38 UTC, closed without merging