add details about being a subscription admin
open-cluster-management-io/policy-collection pull request #164
Opened 2021-10-15 22:03 UTC by gparvin

Signed-off-by: Gus Parvin <gparvin@redhat.com>
We need to say something about being a subscription admin.  I added an update to the readme.

2021-10-18 17:28 UTC, dockerymick requested changes

2021-10-18 17:28 UTC, dockerymick commented on README.md
> +errors.  If subscription admin is required, you will see a message similar to the one below for any resource that
There is an extra space before "If". "was not created" is also in a new line. I suggest the following update:

If the subscription administrator role is required, a message similar to the following one appears for any resource that is not created:

2021-10-18 17:28 UTC, dockerymick commented on README.md
> +To become a subscription administrator, you must add an entry for your user to
I suggest to move "the `open-cluster-management:subscription-admin` ClusterRoleBinding." to line 57. i would also monospace, so change ClusterRoleBinding to `ClusterRoleBinding`.

2021-10-18 22:03 UTC, gparvin commented on README.md
> +errors.  If subscription admin is required, you will see a message similar to the one below for any resource that
Thanks, I made this update.

2021-10-18 22:03 UTC, gparvin commented on README.md
> +To become a subscription administrator, you must add an entry for your user to
I made this update.  Take a look when you get a chance. @dockerymick

2021-10-19 16:31 UTC, dockerymick approved these changes
looks good to me, thanks Gus!

2021-10-19 16:32 UTC, merged