Add policy generator examples
open-cluster-management-io/policy-collection pull request #201
Opened 2021-12-13 22:16 UTC by dhaiducek

2021-12-13 22:16 UTC, dhaiducek commented
/hold for review

2021-12-14 21:08 UTC, mprahl requested changes

2021-12-14 21:08 UTC, mprahl commented on README.md
> +In new versions of Open Cluster Management you must be a subscription administrator in order to
Ideally, these formatting changes should be in separate commits. One reason is it makes review easier since I know all changes in a particular commit are auto-formatting changes. The other is in the event that we revert the policy generator example commit, it'd also revert the formatting changes.

I'll let this slide this review but please keep this in mind for future PRs.

2021-12-14 21:08 UTC, mprahl commented on generator/README.md
> +## Additional information
It might be good to also link the 2.4 product documentation to the policy generator

2021-12-14 21:08 UTC, mprahl commented on generator/README.md
> +- [`subscription.yaml`](subscription.yaml) - Manifest to deploy the Subscription/Channel resources
```suggestion
- [`subscription.yaml`](subscription.yaml) - Manifest to deploy the Subscription/Channel resource objects
```

2021-12-14 21:08 UTC, mprahl commented on generator/README.md
> +  - [`policy2_gatekeeper/`](kustomize/policy2_gatekeeper) - Gatekeeper manifests to wrap in a policy
```suggestion
  - [`policy2_gatekeeper/`](kustomize/policy2_gatekeeper) - Gatekeeper policy manifests to wrap in a policy (assumes Gatekeeper is installed)
```

2021-12-14 21:08 UTC, mprahl commented on generator/README.md
> +  - [`policy3_kyverno/`](kustomize/policy3_kyverno) - Kyverno manifests to wrap in a policy (assumes
```suggestion
  - [`policy3_kyverno/`](kustomize/policy3_kyverno) - Kyverno policy manifests to wrap in a policy (assumes
```

2021-12-14 21:08 UTC, mprahl commented on generator/README.md
> +- Clone this repository (or a fork of it).
```suggestion
- Clone this repository or a fork of it, but a fork will require the Git URL to be modified in [`subscription.yaml`](subscription.yaml).
```

2021-12-14 21:08 UTC, mprahl commented on generator/README.md
> +- Navigate to the Governance tab of your hub to view the deployed policies!
```suggestion
- Navigate to the Governance tab of your hub to view the deployed policies! Note that this can take a few minutes.
```

2021-12-14 21:08 UTC, mprahl commented on generator/kustomize/policyGenerator.yaml
> +  remediationAction: inform
Setting the remediation action to `inform` is the right call but could you please document that it is set to `inform`?

2021-12-16 21:07 UTC, dhaiducek commented on generator/README.md
> +- Clone this repository (or a fork of it).
I think I'll remove the fork reference entirely in favor of the last step instructing to fork in order to customize it, which also has the instructions about the git path.

2021-12-16 21:08 UTC, dhaiducek commented on generator/README.md
> +- [`subscription.yaml`](subscription.yaml) - Manifest to deploy the Subscription/Channel resources
Darn it! Back to my old habits. 🙂

2021-12-16 21:09 UTC, dhaiducek commented on README.md
> +In new versions of Open Cluster Management you must be a subscription administrator in order to
Good tip. I'm going to go ahead and not let it slide. 🙂

2021-12-17 13:41 UTC, mprahl commented
@dhaiducek This looks great! Ideally, this would be two commits. One being the auto-formatting and the other is the Policy Generator documentation/examples.

It looks like we may only have the "squash and merge" option in this repo. I can't verify though since I don't have access. So we can either live with the fact that your effort for separating the commits will not make it to the main branch or you can enable the "rebase and merge" option and then squash the last three commits.

2021-12-17 13:42 UTC, mprahl approved these changes, later dismissed
/hold for decision on merge strategy

2021-12-17 15:11 UTC, mprahl approved these changes
Nice!

2021-12-17 15:15 UTC, merged