policy-deployment
open-cluster-management-io/policy-collection pull request #23
Opened 2020-09-04 11:27 UTC by ch-stark

This example is the basis for further examples like HPA and PodDisruptionBudgets
Usecase: How to ensure that x Pods are running

tested it works
NAME                                READY   STATUS    RESTARTS   AGE
nginx-deployment-6b474476c4-8nfmw   1/1     Running   0          2m48s
nginx-deployment-6b474476c4-9km2g   1/1     Running   0          11m
nginx-deployment-6b474476c4-mz5p8   1/1     Running   0          14s
nginx-deployment-6b474476c4-tdb54   1/1     Running   0          11m
nginx-deployment-6b474476c4-x6lbd   1/1     Running   0          14s

2020-09-04 11:27 UTC, ch-stark commented
/assign @jrnp7

2020-09-29 15:29 UTC, ycao56 commented on community/CM-Configuration-Management/policy-deployment-sample.yaml
> +    policy.open-cluster-management.io/standards: NIST-CSF
change standards/categrories/controls to NIST 800-53

2020-09-29 18:05 UTC, dockerymick requested changes

2020-09-29 18:05 UTC, dockerymick commented on community/README.md
> +    <td><a href="./CM-Configuration-Management/policy-deployment-sample.yaml">Example of creating a Deployment Object.</a> This example generates 5 replicas of nginx-pods </td>
Instead of the comma after Object, use a colon (:)

Add backticks around nginx-pods. For example (`) nginx-pods --> `nginx-pod`. Also add a period at the end of your statement. Please update to the following statement: 


Example of creating a Deployment Object:</a> This example generates 5 replicas of `nginx-pods`.

2020-09-29 18:05 UTC, dockerymick commented on community/README.md
> +    <td>See the <a href "https://kubernetes.io/docs/concepts/workloads/controllers/deployment/"> Kubernetes Documentation </a> to learn more about Deployments.</td>
When viewed this file and selected Kubernetes Documentation, the link took me to the community folder of the policy-collection repo: https://github.com/open-cluster-management/policy-collection/tree/fce73ceb5befc3e087aa26d63bfbfe9bd6c0b6ae/community

2020-09-29 18:33 UTC, dockerymick approved these changes
Thanks for the update @ch-stark, the links work well now. i also made a small update

2020-09-29 21:38 UTC, ycao56 commented on community/CM-Configuration-Management/policy-deployment-sample.yaml
> +    policy.open-cluster-management.io/categories: PR.PT Protective Technology
@ch-stark this is not NIST 800-53 categories

2020-09-29 21:38 UTC, ycao56 commented on community/CM-Configuration-Management/policy-deployment-sample.yaml
> +    policy.open-cluster-management.io/controls: PR.PT-3 Least Functionality
@ch-stark this is not NIST 800-53 controls

2020-09-30 12:40 UTC, merged