Implement `--dry-run` and `--deploy-app` flags for `deploy.sh`
open-cluster-management-io/policy-collection pull request #245
Opened 2022-03-15 21:35 UTC by dhaiducek

- `deploy.sh` outputs the resulting Subscription manifests to a file every time, regardless of whether in dry-run mode or not
- `--dry-run` - Output the result to `stdout` but don't apply it to the cluster (also saves the result to `manifests.yaml`
- `--deploy-app` - Deploy an Application manifest for additional visibility in the UI
- Updates to the various `README.md` for these changes as well as clarifications around the generator and PolicySets

2022-03-17 18:58 UTC, gparvin requested changes

2022-03-17 18:58 UTC, gparvin commented on deploy/deploy.sh
> +# Check for the namespace
Should the namespace be created in a dry run scenario?

2022-03-17 19:00 UTC, dhaiducek commented on deploy/deploy.sh
> +# Check for the namespace
Ooo, you're right--good catch!

2022-03-18 13:02 UTC, gparvin commented
/lgtm
This looks like great stuff!  Thanks for the updates.

2022-03-18 14:20 UTC, dhaiducek commented
/hold I'm not 100% sure we should add the Application feature: https://coreos.slack.com/archives/C027TN14SGJ/p1647613171020129?thread_ts=1647612794.419359&cid=C027TN14SGJ

2022-03-18 17:10 UTC, dhaiducek commented
Okay, PlacementRule added. (Which we'll have to update to Placement eventually, but that might be a task for another day...) Please take another look. The logic flows got a little bit more complex with Placement in the mix, but I'm not sure about alternative tooling (or Kustomize features I may not be using).

2022-03-18 19:42 UTC, gparvin commented
Ah, yes, so you want it to look nice in the Topology part of App Lifecycle.  It will be a nice thing to show off in the sync call too.
/lgtm

2022-03-19 11:13 UTC, dhaiducek commented
/unhold

2022-03-21 02:15 UTC, gparvin approved these changes

2022-03-21 02:18 UTC, merged