This is a MachineSets policy that is useful for OCS on AWS
open-cluster-management-io/policy-collection pull request #246
Opened 2022-03-16 13:23 UTC by gparvin

To install OCS on an AWS cluster you need some extra `MachineSets`
that will be used by OCS.  This policy shows how to use templates to
easily create the MachineSets with the cluster name and region
configured using templates.  The AMI ID does have to be updated to
a proper value for your AWS region and OpenShift version.

Signed-off-by: Gus Parvin <gparvin@redhat.com>

2022-03-16 13:24 UTC, gparvin commented
/cc @ch-stark

2022-03-18 13:40 UTC, gparvin commented
This should resolve issue https://github.com/stolostron/backlog/issues/20571

2022-03-21 18:26 UTC, ycao56 requested changes

2022-03-21 18:26 UTC, ycao56 commented on community/CM-Configuration-Management/policy-aws-machine-sets.yaml
> +  name: policy-ocs-machinesets
Missing annotations

2022-03-21 18:27 UTC, ycao56 commented on community/CM-Configuration-Management/policy-aws-machine-sets.yaml
> +          namespaceSelector:
This can be omitted

2022-03-21 21:44 UTC, gparvin commented on community/CM-Configuration-Management/policy-aws-machine-sets.yaml
> +  name: policy-ocs-machinesets
I added the annotations

2022-03-21 21:44 UTC, gparvin commented on community/CM-Configuration-Management/policy-aws-machine-sets.yaml
> +          namespaceSelector:
Removed.

2022-03-21 21:44 UTC, gparvin commented
Thanks @ycao56  Changes made.

2022-03-21 22:10 UTC, ycao56 approved these changes

2022-03-21 22:11 UTC, merged