[WIP] add gatekeeper policyset
open-cluster-management-io/policy-collection pull request #345
Opened 2022-09-23 15:28 UTC by ch-stark

first draft

2022-09-23 17:49 UTC, gparvin reviewed
I mostly just reviewed the readme for now.  Are we going to create multitenancy and application policy sets for gatekeeper too?

2022-09-23 17:49 UTC, gparvin commented on community/CM-Configuration-Management/policy-gatekeeper-config-exclude-namespaces.yaml
> +                        - openshift-cloud-network-config-controller
I just created a separate PR for these changes: https://github.com/stolostron/policy-collection/pull/347
I think I've added in a few you don't have.

2022-09-23 17:49 UTC, gparvin commented on policygenerator/policy-sets/community/gatekeeper/README.md
> +- Security
More detail: maybe:  Applies Kubernetes security best practices to your cluster.

2022-09-23 17:49 UTC, gparvin commented on policygenerator/policy-sets/community/gatekeeper/README.md
> +When using ACM-Subscriptions and Placement we strongly recommend to install the following policies before you apply the Policy (Policies need to be set to enforce)
```suggestion
When using ACM-Subscriptions and Placement we strongly recommend to install the following policies before you apply this `PolicySet` (These policies need to be set to enforce after installation)
```

2022-09-23 17:49 UTC, gparvin commented on policygenerator/policy-sets/community/gatekeeper/README.md
> +![Policies](images/policies-installed.png)
Remove this or add the image - also there are other images referenced below that need to be added or not referenced

2022-09-23 17:49 UTC, gparvin commented on policygenerator/policy-sets/community/gatekeeper/README.md
> +Now you can create three Applications in RHACM-UI where every Application corresponds to a path under `policy-sets/community/kyverno`
Update for gatekeeper

2022-09-26 10:23 UTC, ch-stark commented on community/CM-Configuration-Management/policy-gatekeeper-config-exclude-namespaces.yaml
> +                        - openshift-cloud-network-config-controller
thanks

2022-11-13 21:41 UTC, dlbewley requested changes

2022-11-13 21:41 UTC, dlbewley commented on policygenerator/policy-sets/community/gatekeeper/README.md
> +Now you can create the Applications in the RHACM-UI where the Application corresponds to the path under `policy-sets/community/gatekeeper`
It’s not entirely obvious what placement to use for the Subscription being created in this step. I inferred 'local-cluster' and namespace 'policies' from screenshots, but it might be helpful to make that explicit.

2022-11-13 21:41 UTC, dlbewley commented on policygenerator/policy-sets/community/gatekeeper/README.md
> +oc apply -f https://raw.githubusercontent.com/stolostron/policy-collection/main/community/CM-Configuration-Management/policy-gatekeeper-config-exclude-namespaces.yaml
I found that even though a violation was detected this policy did not seem to propagate.

Modifying in the UI to temporarily disable the policy divulged an error:

_The combined length of namespace and policy name (namespaceName.policyName) should not exceed 63 characters_

```
echo 'open-cluster-management.policy-gatekeeper-config-exclude-namespaces' | wc -c
      68
```

2022-12-14 15:54 UTC, gparvin commented on policygenerator/policy-sets/community/gatekeeper/policyGenerator.yaml
> +  - description: gatekeeper-policyset to apply set of gatekeeper-policies.
Since the description will appear in the console I think it should be more descriptive like:
A set of open policy agent gatekeeper admission controls that require best practices to be followed for applications being installed onto the managed cluster

2022-12-14 15:57 UTC, gparvin commented on policygenerator/policy-sets/community/gatekeeper/README.md
> +oc apply -f https://raw.githubusercontent.com/stolostron/policy-collection/main/community/CM-Configuration-Management/policy-gatekeeper-config-exclude-namespaces.yaml
Ideally we should remove this policy and encourage users to directly apply this configuration with the operator or helm settings instead of making it a separate policy.

2023-01-13 15:35 UTC, gparvin approved these changes
I added a commit to address the review comments.  I'll add my approval and we'll see if this can be tried out by the community.

2023-01-13 15:38 UTC, merged