Add policy to install the Compliance Operator
open-cluster-management-io/policy-collection pull request #36
Opened 2020-10-23 11:47 UTC by JAORMX

This policy installs the Compliance Operator's upstream release in the
managed clusters. This is done through the OLM by installing the catalog
source pointing to the upstream release, and then installing the
operatorgroup and the subscription.

This addresses the NIST SP 800-53 controls CA-2 and CA-7.

2020-10-23 12:20 UTC, JAORMX commented
Pull-request updated, HEAD is now 1b0f87feed562b11a0daa0a04060c79ae1ae5f15

2020-10-23 12:48 UTC, JAORMX commented
Pull-request updated, HEAD is now 9a7b80b04328b1fa7bfbd89be507c40006663875

2020-10-26 12:57 UTC, ycao56 approved these changes

2020-10-26 13:58 UTC, dockerymick requested changes

2020-10-26 13:58 UTC, dockerymick commented on community/README.md
> +    <td><a href="./CA-Security-Assessment-and-Authorization/policy-compliance-operator-install-upstream.yaml">Install Upstream Compliance Operator policy</a>: Use the "upstream compliance operator in
I suggest to make the following update:

Use the upstream compliance operator installation, `policy-comp-operator` policy, to enable continuous compliance monitoring for your cluster. After you install this operator, you must select what benchmark you want to comply to, and create an appropriate objects for the scans to be ran.

2020-10-26 14:04 UTC, JAORMX commented on community/README.md
> +    <td><a href="./CA-Security-Assessment-and-Authorization/policy-compliance-operator-install-upstream.yaml">Install Upstream Compliance Operator policy</a>: Use the "upstream compliance operator in
Done, thanks for the review.

2020-10-26 14:04 UTC, JAORMX commented
Pull-request updated, HEAD is now ae103b0a8e1cc23b1ef7b4417c4aa2a532926fc7

2020-10-26 19:04 UTC, dockerymick approved these changes

2020-10-26 19:05 UTC, merged