Prep for move to community repository
open-cluster-management-io/policy-collection pull request #371
Opened 2022-11-18 19:30 UTC by gparvin

This creates some simple API validation (which could be enhanced more) and changes ACM specific usage to open cluster management.

I have not changed references to stolostron yet.  I'm thinking that will be a PR to do after the move to avoid breaking links now. Any feedback or PR updates are welcome.

Refs:
 - https://github.com/stolostron/backlog/issues/25068

Signed-off-by: Gus Parvin <gparvin@redhat.com>

2022-11-18 19:41 UTC, dhaiducek commented
I'm not so sure we should make these changes here midstream since we may want to preserve Red Hat references here in `stolostron`. It seems we should migrate the repo, fork it back, and then make the changes upstream to reflect it being upstream?

2022-11-18 19:45 UTC, dhaiducek commented
The changes for upstream overall look good, and that schema validator is a really nice addition! I might move it to a more generic "builds" or "scripts" folder so that we can put other scripts there in the future, though.

2022-11-18 20:53 UTC, dhaiducek commented
/hold

2022-12-02 21:45 UTC, dhaiducek requested changes

2022-12-02 21:45 UTC, dhaiducek commented on policygenerator/policy-sets/stable/README.md
> +[Open Cluster Management Hardening](./openshift-hardening) | Applies best practice policies for your Open Cluster Management hub installation. | Needs to be deployed only to the Open Cluster Manageme
```suggestion
[Open Cluster Management Hardening](./ocm-hardening) | Applies best practice policies for your Open Cluster Management hub installation. | Needs to be deployed only to the Open Cluster Management hub cluster. The `PolicySet` uses cluster `Placement` and not the `PlacementRule` placement mechanism.
```

2022-12-02 21:45 UTC, dhaiducek commented on policygenerator/policy-sets/stable/README.md
> +[Open Cluster Management Hardening](./openshift-hardening) | Applies best practice policies for your Open Cluster Management hub installation. | Needs to be deployed only to the Open Cluster Manageme
Along with this, we'd need to update the name of the directory.

2022-12-07 21:53 UTC, gparvin commented on policygenerator/policy-sets/stable/README.md
> +[Open Cluster Management Hardening](./openshift-hardening) | Applies best practice policies for your Open Cluster Management hub installation. | Needs to be deployed only to the Open Cluster Manageme
@dhaiducek I made changes related to renaming the hardening directory for the community policy and fixed the bad link.  I can't rename stable because we support stable and need to keep the same name until we create a `release-2.6` branch with the supported policy there.  Then we can do the rename and update the automation that tests the stable policy.

2023-01-05 19:25 UTC, gparvin commented on policygenerator/policy-sets/stable/README.md
> +[Open Cluster Management Hardening](./openshift-hardening) | Applies best practice policies for your Open Cluster Management hub installation. | Needs to be deployed only to the Open Cluster Manageme
@dhaiducek As discussed I have removed the OCM specific changes for now with the goal of using magic mirror so we can have differences in upstream and midstream readme content.  Take a look to see if things look ok now.
Thanks!

2023-01-09 19:03 UTC, mprahl commented on build/validate-policies.sh
> +	curl -o crd-schema.py https://raw.githubusercontent.com/yannh/kubeconform/master/scripts/openapi2jsonschema.py
Could you please use a tagged version or a specific commit?

2023-01-09 19:04 UTC, mprahl commented on build/validate-policies.sh
> +	curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
Could you use `go install` instead? Also please use a tagged version.

2023-01-09 19:06 UTC, mprahl commented on build/validate-policies.sh
> +if [ ! -f ~/.config/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator/PolicyGenerator ]; then
Could you set the `KUSTOMIZE_PLUGIN_HOME` environment variable instead of using the home directory to store the Policy Generator?

2023-01-09 21:17 UTC, gparvin commented on build/validate-policies.sh
> +if [ ! -f ~/.config/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator/PolicyGenerator ]; then
ok, I got this working with the latest changes.  Thanks for suggesting this.

2023-01-09 21:17 UTC, gparvin commented on build/validate-policies.sh
> +	curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
Done

2023-01-09 21:17 UTC, gparvin commented on build/validate-policies.sh
> +	curl -o crd-schema.py https://raw.githubusercontent.com/yannh/kubeconform/master/scripts/openapi2jsonschema.py
Done

2023-01-10 14:50 UTC, mprahl commented
@gparvin could you please squash your commits?

2023-01-10 14:51 UTC, mprahl commented on build/validate-policies.sh
> +if [ ! -f ~/.config/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator/PolicyGenerator ]; then
@gparvin you'll need to update this if statement now to use the `KUSTOMIZE_PLUGIN_HOME` environment variable value.

2023-01-10 15:18 UTC, dhaiducek commented on build/validate-policies.sh
> +	GOBIN=$(pwd)/ GO111MODULE=on go install sigs.k8s.io/kustomize/kustomize/v4@$KUSTOMIZE_VERSION
For other flows, we use:
```
export GOBIN=${PWD}/bin
export PATH := ${GOBIN}:${PATH}
```

Maybe use that at the top of the file instead? (Especially since eventually we may want to do a `go install`  here once the generator is migrated upstream.)

2023-01-10 15:18 UTC, dhaiducek commented on build/validate-policies.sh
> +if [ ! -f ~/.config/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator/PolicyGenerator ]; then
Given the change, shouldn't this line be:
```suggestion
if [ ! -f ${KUSTOMIZE_PLUGIN_HOME}/policy.open-cluster-management.io/v1/policygenerator/PolicyGenerator ]; then
```

2023-01-10 18:50 UTC, dhaiducek reviewed
Nit: I'm still not convinced the ACM references should be updated to OCM in this PR?

2023-01-13 14:53 UTC, gparvin commented on build/validate-policies.sh
> +	GOBIN=$(pwd)/ GO111MODULE=on go install sigs.k8s.io/kustomize/kustomize/v4@$KUSTOMIZE_VERSION
Thanks, I've made updates to use GOBIN.

2023-01-13 14:54 UTC, gparvin commented
> Nit: I'm still not convinced the ACM references should be updated to OCM in this PR?

@dhaiducek I thought I had removed those references.  As you pointed out there were some more which I have now removed.  Thanks!

2023-01-13 21:13 UTC, dhaiducek reviewed
Looking good! I don't recall if I said it before, but thanks for all the link updates!

I have a suggestion around dynamically setting the GitHub org.

2023-01-13 21:13 UTC, dhaiducek commented on build/validate-policies.sh
> +	./crd-schema.py https://raw.githubusercontent.com/open-cluster-management-io/api/main/cluster/v1beta1/0000_02_clusters.open-cluster-management.io_placements.crd.yaml
These should probably point to `stolostron` also. Maybe put it in a variable here and then update the workflow with `export GITHUB_ORG=${{ github.repository_owner }}`? That way, all files can be the same in all orgs.
```suggestion
	GITHUB_ORG=${GITHUB_ORG:-"open-cluster-management-io"}
	./crd-schema.py https://raw.githubusercontent.com/${GITHUB_ORG}/governance-policy-propagator/main/deploy/crds/policy.open-cluster-management.io_policies.yaml
	./crd-schema.py https://raw.githubusercontent.com/${GITHUB_ORG}/governance-policy-propagator/main/deploy/crds/policy.open-cluster-management.io_placementbindings.yaml
	./crd-schema.py https://raw.githubusercontent.com/${GITHUB_ORG}/api/main/cluster/v1beta1/0000_02_clusters.open-cluster-management.io_placements.crd.yaml
```

2023-01-13 21:13 UTC, dhaiducek commented on build/validate-policies.sh
> +	curl -L -o generator https://github.com/stolostron/policy-generator-plugin/releases/latest/download/${PLATFORM}-amd64-PolicyGenerator
Side note: We seriously need to get the generator upstream...

2023-01-16 16:38 UTC, gparvin commented on build/validate-policies.sh
> +	./crd-schema.py https://raw.githubusercontent.com/open-cluster-management-io/api/main/cluster/v1beta1/0000_02_clusters.open-cluster-management.io_placements.crd.yaml
I made an update to use a common org.  Hopefully it will match the right one if I understand the doc correctly. THanks!

2023-01-16 20:03 UTC, dhaiducek requested changes
I didn't think about the environment variable already being available! Does removing the new `export` and using `GITHUB_REPOSITORY_OWNER` instead of `GITHUB_ORG` work?

2023-01-20 14:14 UTC, gparvin commented
> I didn't think about the environment variable already being available! Does removing the new `export` and using `GITHUB_REPOSITORY_OWNER` instead of `GITHUB_ORG` work?

@dhaiducek I changed it as requested but take a look and see if it's ok now.

2023-01-20 21:33 UTC, dhaiducek approved these changes
LGTM! Thanks, @gparvin!

2023-01-20 21:57 UTC, gparvin commented
/unhold

2023-01-20 22:01 UTC, merged