Vsphere policies
open-cluster-management-io/policy-collection pull request #375
Opened 2022-12-02 12:57 UTC by fperearodriguez

Adding two ACM policies :

Create a MachineSet in a vSphere environment for creating infrastructure nodes.
Create and configure the OAuth in Openshift. Besides, create a cronjob to sync Openshift with an external IDP.

2022-12-02 21:16 UTC, dhaiducek requested changes
Thank you for your contribution! I have some minor comments to consider.

2022-12-02 21:16 UTC, dhaiducek commented on community/README.md
> +[Policy to configure the OAuth in OpenShift and sync with LDAP](./CM-Configuration-Management/policy-oauth-ldapsync.yaml) | Adds some objects to configure the OAuth in a OpenShift cluster by using an
```suggestion
[Policy to configure the OAuth in OpenShift and sync with LDAP](./CM-Configuration-Management/policy-oauth-ldapsync.yaml) | Adds some objects to configure the OAuth in an OpenShift cluster by using an external IDP and htpasswd. In addition to this, a CronJob is created to sync the OpenShift cluster with an external LDAP. | OpenShift 4.x is required. For more information on configuring the OAuth clients, see the OpenShift documentation: [Configuring the LDAP identity provider](https://docs.openshift.com/container-platform/4.10/authentication/identity_providers/configuring-ldap-identity-provider.html)
```

2022-12-02 21:16 UTC, dhaiducek commented on community/CM-Configuration-Management/policy-oauth-ldapsync.yaml
> +  remediationAction: enforce
Please use `inform` here as a default. We prefer to leave it up to users to enforce policies.

2022-12-02 21:16 UTC, dhaiducek commented on community/CM-Configuration-Management/policy-vsphere-machine-set.yaml
> +      - key: entorno
Optional: Use "environment" as the key. (Though I personally like having another language represented in our repo, so updating this truly is optional. 🙂 )

2022-12-02 21:16 UTC, dhaiducek commented on community/CM-Configuration-Management/policy-oauth-ldapsync.yaml
> +# This policy configures the oauth for htpasswd and ldap provider, and create a job to sync with an external LDAP.
```suggestion
# This policy configures the oauth for htpasswd and ldap provider, and creates a job to sync with an external LDAP.
```

2022-12-02 21:16 UTC, dhaiducek commented on community/CM-Configuration-Management/policy-oauth-ldapsync.yaml
> +          severity: high
The links point to LDAP, so I might prefer that the `htpasswd` references either be removed or moved to a separate policy to keep it simpler/more focused. Would that make sense? Or does htpasswd go hand-in-hand with LDAP somehow?

2022-12-02 21:16 UTC, dhaiducek commented on community/CM-Configuration-Management/policy-vsphere-machine-set.yaml
> +# This policy creates 1 OpenShift MachineSet that are intended for infrastructure workloads.
Would you please add brief details about the values that should be replaced in the policy? I don't have familiarity with vSphere, so it could be obvious to a vSphere user, but it'd be nice to have a note that this policy needs to be updated before use.

2022-12-02 21:16 UTC, dhaiducek commented on community/CM-Configuration-Management/policy-oauth-ldapsync.yaml
> +# In this example, Active Directory is used as external IDP.
Would you please add a brief note about what needs to be updated in this Policy to connect it with an LDAP instance?

2022-12-05 11:26 UTC, fperearodriguez commented on community/README.md
> +[Policy to configure the OAuth in OpenShift and sync with LDAP](./CM-Configuration-Management/policy-oauth-ldapsync.yaml) | Adds some objects to configure the OAuth in a OpenShift cluster by using an
Done

2022-12-05 11:28 UTC, fperearodriguez commented on community/CM-Configuration-Management/policy-oauth-ldapsync.yaml
> +  remediationAction: enforce
Changed to `inform` in the three policies created in this PR.

2022-12-05 11:29 UTC, fperearodriguez commented on community/CM-Configuration-Management/policy-vsphere-machine-set.yaml
> +      - key: entorno
My mistake. Changed to `environment`.

2022-12-05 11:29 UTC, fperearodriguez commented on community/CM-Configuration-Management/policy-oauth-ldapsync.yaml
> +# This policy configures the oauth for htpasswd and ldap provider, and create a job to sync with an external LDAP.
Done.

2022-12-05 11:35 UTC, fperearodriguez commented on community/CM-Configuration-Management/policy-oauth-ldapsync.yaml
> +          severity: high
I moved the `htpasswd` configuration to a new policy. I agree with you, it is easier this way. Thanks!

2022-12-05 11:37 UTC, fperearodriguez commented on community/CM-Configuration-Management/policy-vsphere-machine-set.yaml
> +# This policy creates 1 OpenShift MachineSet that are intended for infrastructure workloads.
Sure. I've added more details in all the policies added in this PR.

2022-12-05 11:38 UTC, fperearodriguez commented on community/CM-Configuration-Management/policy-oauth-ldapsync.yaml
> +# In this example, Active Directory is used as external IDP.
Done

2022-12-05 14:28 UTC, dhaiducek commented on community/CM-Configuration-Management/policy-oauth-ldapsync.yaml
> +          severity: high
Thanks! Would you please also add a line in the README for the new policy?

2022-12-05 14:37 UTC, dhaiducek reviewed
The updated descriptions are fantastic--thanks for the updates and additional details!

2022-12-05 14:37 UTC, dhaiducek commented on community/CM-Configuration-Management/policy-oauth-htpasswd.yaml
> +            - complianceType: mustonlyhave
Optional: Setting the `complianceType` to `mustonlyhave` would replace any existing OAuth configurations (which is fine and in many cases desirable), but this (and/or the LDAP OAuth) could optionally be updated to `musthave` to merge `identityProviders`.

2022-12-05 17:46 UTC, fperearodriguez commented on community/CM-Configuration-Management/policy-oauth-ldapsync.yaml
> +          severity: high
Of course, README updated.

2022-12-05 17:47 UTC, fperearodriguez commented on community/CM-Configuration-Management/policy-oauth-htpasswd.yaml
> +            - complianceType: mustonlyhave
Totally agree by merging configuration instead of replacing. Thanks!

2022-12-05 19:08 UTC, dhaiducek approved these changes
Looks great! Thank you for your contributions and making the updates!

2022-12-05 19:13 UTC, merged