Add etcd backup policy using default storage class
open-cluster-management-io/policy-collection pull request #38
Opened 2020-10-23 18:42 UTC by dav1x

This policy adds ETCD backups using the clusters default storage class.

2020-10-26 11:30 UTC, ch-stark commented
some ideas regarding readme:
We use the etcd container image because it contains all required tools like etcdctl.
From the pod we  we are running the etcd backup and keeping last 6 backup snapshots.

2020-10-26 13:11 UTC, ycao56 commented
@dav1x can you add some readme to explain what this policy does?

2020-10-26 13:12 UTC, ycao56 commented on community/SI-System-and-Information-Integrity/policy-etcd-backup.yaml
> +  namespace: openshift-config
remove ns

2020-10-26 13:13 UTC, ycao56 commented on community/SI-System-and-Information-Integrity/policy-etcd-backup.yaml
> +          namespaceSelector:
when you hardcode namespace in object-templates or object is a cluster scope resource. namespaceSelector will be ignored and can be omitted in policy yaml

2020-10-26 13:59 UTC, ch-stark commented
Regarding Docu:
The policy uses the etcd container image because it contains all required tools like etcdctl
It uses the shell command which will be executed by the pod. 
In this case, it is running the etcd backup and keeps the last 6 backup snapshots.

2020-10-26 14:01 UTC, dav1x commented on community/SI-System-and-Information-Integrity/policy-etcd-backup.yaml
> +          namespaceSelector:
done. sorry

2020-10-27 15:31 UTC, ycao56 commented
can you resolve the conflicts? we updated the table to use markdown table instead

2020-10-27 15:35 UTC, dav1x commented
I just noticed that and updated. Thanks for the quick responses.

2020-10-27 15:44 UTC, ycao56 approved these changes

2020-10-27 15:45 UTC, ycao56 commented on community/SI-System-and-Information-Integrity/policy-etcd-backup.yaml
> +  name: binding-policy-disallowed-roles
better rename it to match your policy name

2020-10-27 15:46 UTC, ycao56 commented on community/SI-System-and-Information-Integrity/policy-etcd-backup.yaml
> +- name: policy-disallowed-roles
need to match policy name

2020-10-27 15:46 UTC, ycao56 commented on community/SI-System-and-Information-Integrity/policy-etcd-backup.yaml
> +  name: placement-policy-disallowed-roles
better rename it to match your policy name

2020-10-27 15:46 UTC, ycao56 commented on community/SI-System-and-Information-Integrity/policy-etcd-backup.yaml
> +  name: placement-policy-disallowed-roles
need to match placementrule name if renamed

2020-10-27 20:40 UTC, dockerymick requested changes

2020-10-27 20:40 UTC, dockerymick commented on community/README.md
> +[ETCD Backup](./SI-System-and-Information-Integrity/policy-backup-etcd.yaml) | The policy uses the etcd container image because it contains all required tools like etcdctl. It uses the shell command
Use the ETCD Backup policy to receive the last six backup snapshots for etcd. This policy uses the etcd container image in the policy because it contains all required tools like `etcdctl`. | For more information, see [OpenShift 4 with default storage class](https://docs.openshift.com/container-platform/4.5/storage/dynamic-provisioning.html).

2020-10-27 20:50 UTC, dav1x commented on community/SI-System-and-Information-Integrity/policy-etcd-backup.yaml
> +  name: placement-policy-disallowed-roles
done

2020-10-27 22:12 UTC, dockerymick approved these changes
Changes look good to me, thanks!

2020-10-28 13:20 UTC, ycao56 requested changes

2020-10-28 13:20 UTC, ycao56 commented on community/README.md
> +[ETCD Backup](./SI-System-and-Information-Integrity/policy-backup-etcd.yaml) | Use the ETCD Backup policy to receive the last six backup snapshots for etcd. This policy uses the etcd container image
just noticed the policy is categorized as CM but the description is under `System and Information Integrit`. Can you fix it?

2020-10-28 13:56 UTC, dav1x commented on community/README.md
> +[ETCD Backup](./SI-System-and-Information-Integrity/policy-backup-etcd.yaml) | Use the ETCD Backup policy to receive the last six backup snapshots for etcd. This policy uses the etcd container image
I fixed it. I moved it under CM. I think that it makes more sense there since its for configuration.

2020-10-28 13:59 UTC, ycao56 approved these changes

2020-10-28 13:59 UTC, merged