Add missing CRDs to validate script
open-cluster-management-io/policy-collection pull request #410
Opened 2023-05-04 21:08 UTC by gparvin

We haven't needed `PolicySet` or `PolicyAutomation` in the PR validation until now.  We should allow these CRs to be candidates for community policy submissions so I have added them to the script.

Refs:
 - https://github.com/open-cluster-management-io/policy-collection/pull/409

2023-05-05 13:16 UTC, dhaiducek requested changes
Since we're here...would you also update the policy generator link to use `GITHUB_REPOSITORY_OWNER` now that we have forked versions?

2023-05-08 12:28 UTC, gparvin commented
@dhaiducek Sure thing!   Updated the link.

2023-05-08 12:43 UTC, dhaiducek approved these changes
/hold Thanks! I realized now that I see the update that `stolostron` doesn't have GitHub releases, so we can either roll with this and figure that out later or set it directly to `open-cluster-management-io` for now...

2023-05-08 17:58 UTC, gparvin commented
The command worked for me so will merge this for now.
/unhold

2023-05-08 18:01 UTC, merged