Update cluster-upgrade policy example
open-cluster-management-io/policy-collection pull request #418
Opened 2023-05-30 20:03 UTC by bellpr

- Add `spec.desiredUpdate.image` for cases when a previous upgrade has left the field populated
- Add a documentation blurb explaining the cases in which `spec.desiredUpdate.image` can be omitted
- Updated `spec.channel` and `spec.desiredUpdate` to a current, supported verion of OpenShift

2023-05-30 20:21 UTC, dhaiducek requested changes
Thanks for the update @bellpr! I have a minor doc update about the image.

2023-05-30 20:22 UTC, dhaiducek commented on community/README.md
> +[Upgrade OpenShift-Cluster Sample policy](./CM-Configuration-Management/policy-upgrade-openshift-cluster.yaml) | Use this policy as an example for upgrading OpenShift clusters with a policy. | OpenSh
Would you please note that the image SHA provided is for `x86_64` architecture? (or provide the tag, though I realize the latter is potentially less deterministic)

2023-05-30 21:20 UTC, bellpr commented on community/README.md
> +[Upgrade OpenShift-Cluster Sample policy](./CM-Configuration-Management/policy-upgrade-openshift-cluster.yaml) | Use this policy as an example for upgrading OpenShift clusters with a policy. | OpenSh
@dhaiducek I added a note mentioning the version and arch of the image, does that sufficiently address your request? I haven't tested with a tag, so I hesitate to go that route.

2023-05-30 21:22 UTC, dhaiducek commented on community/README.md
> +[Upgrade OpenShift-Cluster Sample policy](./CM-Configuration-Management/policy-upgrade-openshift-cluster.yaml) | Use this policy as an example for upgrading OpenShift clusters with a policy. | OpenSh
That's perfect--thanks!

Since we merge pull requests using rebase, please squash the two commits into one, and we'll merge it in!

2023-05-30 21:33 UTC, bellpr commented on community/README.md
> +[Upgrade OpenShift-Cluster Sample policy](./CM-Configuration-Management/policy-upgrade-openshift-cluster.yaml) | Use this policy as an example for upgrading OpenShift clusters with a policy. | OpenSh
Done. Please let me know if there's anything else I can provide.

2023-05-31 00:31 UTC, dhaiducek approved these changes
LGTM! Thanks for the update, @bellpr!

2023-05-31 00:34 UTC, merged