rename policies
open-cluster-management-io/policy-collection pull request #450
Opened 2024-02-01 16:07 UTC by birsanv

Changes:
- rename policies and policy set to remove the volsync from name
- rename `cluster.open-cluster-management.io/volsync` label to `cluster.open-cluster-management.io/backup-hub-pvc`
- updated Readme

2024-02-01 22:26 UTC, dhaiducek requested changes
Thanks for the update! I have some wording/formatting suggestions.

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/README.md
> +# ACM Hub PV backup and restore using volsync
(optional) I personally prefer defining acronyms before using them, but it's not required. Also, is "volsync" officially stylized that way or should it be "VolSync"?

```suggestion
# ACM Hub PersistentVolume backup and restore using VolSync
```

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/README.md
> +Hub PVC backup and restore using volsync with the restic mover feature. This leverages CSI volume snapshot.
```suggestion
Hub PersistentVolumeClaim (PVC) backup and restore using VolSync with the Restic-based mover feature. This leverages the Container Storage Interface (CSI) volume snapshot.
```

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/README.md
> +![Volsync PolisySet](images/policyset.png)
```suggestion
![VolSync PolicySet](images/policyset.png)
```

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/README.md
> +[acm-hub-pvc-backup-config](./acm-hub-pvc-backup-config.yaml)                       | Trigerred to run on the hub only if the hub has any PVCs with the `cluster.open-cluster-management.io/backup-hub-
```suggestion
[acm-hub-pvc-backup-config](./acm-hub-pvc-backup-config.yaml)                       | Triggered to run on the hub only if the hub has any PVCs with the `cluster.open-cluster-management.io/backup-hub-pvc` label. It installs the volsync-addon on the hub or any managed cluster matching the `acm-hub-pvc-backup-policyset` PolicySet's placement. It reports on policy missing configuration: reports if the user had not create the `acm-hub-pvc-backup-restic-secret` Secret and `hub-pvc-backup` ConfigMap resources under the PolicySet namespace. The Secret is used by volsync to connect to the storage location where the PVC snapshot is stored. The `hub-pvc-backup` ConfigMap is used to define the ReplicationSource configuration, as defined in the [RHACM VolSync documentation](https://access.redhat.com/login?redirectTo=https%3A%2F%2Faccess.redhat.com%2Fdocumentation%2Fen-us%2Fred_hat_advanced_cluster_management_for_kubernetes%2F2.8%2Fhtml%2Fbusiness_continuity%2Fbusiness-cont-overview%23restic-backup-volsync). You can provide a custom configuration file for a PVC by creating the `hub-pvc-backup-pvcns-pvcname` ConfigMap under the PolicySet namespace; this will overwrite the default `hub-pvc-backup` ConfigMap for the specified volume.
```

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/README.md
> +```
```suggestion
```yaml
```

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/README.md
> +```
```suggestion
```yaml
```

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/README.md
> +```
```suggestion
```yaml
```

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/README.md
> +```
```suggestion
```yaml
```

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/README.md
> +```
```suggestion
```yaml
```

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/README.md
> +```
```suggestion
```yaml
```

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/README.md
> +```
```suggestion
```yaml
```

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/README.md
> +The `acm-hub-pvc-backup-config` Policy validates the configuration for both types of hubs ( backup or restore ). If any PVC is found with the cluster.open-cluster-management.io/backup-hub-pvc label,
I don't follow this phrase about the "Policy namespace". Are there some missing details or extra words here?
> it installs the volsync addon and verifies the user has created the Policy namespace the `acm-hub-pvc-backup-restic-secret` Secret

```suggestion
The `acm-hub-pvc-backup-config` Policy validates the configuration for both types of hubs (backup or restore). If any PVC is found with the `cluster.open-cluster-management.io/backup-hub-pvc` label, it installs the volsync addon and verifies the user has created the Policy namespace the `acm-hub-pvc-backup-restic-secret` Secret, used to connect to the storage where the snapshot are saved.It also verifies if the user has created the `hub-pvc-backup` ConfigMap used to define the `ReplicationSource` configuration.
```

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/README.md
> +Used to define the volsync ReplicationSource configuration, as defined [here](https://access.redhat.com/login?redirectTo=https%3A%2F%2Faccess.redhat.com%2Fdocumentation%2Fen-us%2Fred_hat_advanced_clu
```suggestion
- Created by the user on the backup hub. 
- Used to define the volsync ReplicationSource configuration, as defined in the [RHACM VolSync documentation](https://access.redhat.com/login?redirectTo=https%3A%2F%2Faccess.redhat.com%2Fdocumentation%2Fen-us%2Fred_hat_advanced_cluster_management_for_kubernetes%2F2.8%2Fhtml%2Fbusiness_continuity%2Fbusiness-cont-overview%23restic-backup-volsync)
```

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/README.md
> +properties for a PVC, you should define a ConfigMap using this name convention : `acm-hub-pvc-backup-config-<pvc-ns>-<pvc-name>`
```suggestion
properties for a PVC, you should define a ConfigMap using this name convention: `acm-hub-pvc-backup-config-<pvc-ns>-<pvc-name>` 
```

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/README.md
> +For example, if the PVC `my-pvc` created in namespace `ns-1` should be backed up every 5 hours, create this ConfigMap under the `open-cluster-management-backup` namespace :
```suggestion
For example, if the PVC `my-pvc` created in namespace `ns-1` should be backed up every 5 hours, create this ConfigMap under the `open-cluster-management-backup` namespace:
```

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/README.md
> +Used to define the volsync ReplicationSource configuration, as defined [here](https://access.redhat.com/login?redirectTo=https%3A%2F%2Faccess.redhat.com%2Fdocumentation%2Fen-us%2Fred_hat_advanced_clu
```suggestion
- Created by the user
- Used to define the volsync ReplicationSource configuration, as defined in the [RHACM VolSync documentation](https://access.redhat.com/login?redirectTo=https%3A%2F%2Faccess.redhat.com%2Fdocumentation%2Fen-us%2Fred_hat_advanced_cluster_management_for_kubernetes%2F2.8%2Fhtml%2Fbusiness_continuity%2Fbusiness-cont-overview%23restic-backup-volsync)
```

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/README.md
> +Created by the volsync policy on the backup hub, for each PVC; uses the PVCs settings
I think this might be the intended wording?
```suggestion
Created by the volsync policy on the backup hub for each PVC using the PVC's settings
```

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/README.md
> +
```suggestion
ACM components installed on the hub.
User adds the `cluster.open-cluster-management.io/backup-hub-pvc` label to the PVC to be backed up.

```

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/README.md
> +- [Volsync](https://access.redhat.com/login?redirectTo=https%3A%2F%2Faccess.redhat.com%2Fdocumentation%2Fen-us%2Fred_hat_advanced_cluster_management_for_kubernetes%2F2.8%2Fhtml%2Fbusiness_continuity%
```suggestion
- [RHACM Volsync documentation](https://access.redhat.com/login?redirectTo=https%3A%2F%2Faccess.redhat.com%2Fdocumentation%2Fen-us%2Fred_hat_advanced_cluster_management_for_kubernetes%2F2.8%2Fhtml%2Fbusiness_continuity%2Fbusiness-cont-overview%23restic-backup-volsync)
```

2024-02-01 22:26 UTC, dhaiducek commented on community/CM-Configuration-Management/acm-hub-pvc-backup/acm-hub-pvc-backup-policyset.yaml
> +    - acm-hub-pvc-backup-destination
Trailing newline
```suggestion
    - acm-hub-pvc-backup-destination

```

2024-02-01 22:57 UTC, birsanv commented
thank you for the review @dhaiducek !

2024-02-02 16:22 UTC, birsanv commented
/cc @dhaiducek can I please have another review
Global hub team is waiting for the updates

2024-02-02 17:06 UTC, dhaiducek commented
@birsanv These review comments are unresolved:
- https://github.com/open-cluster-management-io/policy-collection/pull/450/files#r1475217527
- https://github.com/open-cluster-management-io/policy-collection/pull/450/files#r1475223994

Also please squash the commits into one commit and update the title of the commit message to something more descriptive, something like "Remove "volsync" from policy names".

2024-02-02 17:31 UTC, birsanv commented
@dhaiducek thanks ! I resolved the last 2 comments I missed

2024-02-02 17:34 UTC, dhaiducek commented
> @dhaiducek thanks ! I resolved the last 2 comments I missed

Thanks! Also please squash the commits into one commit and update the title of the commit message to something more descriptive, something like "Remove "volsync" from policy names".

2024-02-02 17:58 UTC, closed without merging

2024-02-02 18:14 UTC, dhaiducek commented
Replaced by:
- https://github.com/open-cluster-management-io/policy-collection/pull/452