Add documentation outlining the steps to transition from placementRul…
open-cluster-management-io/policy-collection pull request #491
Opened 2024-07-12 14:30 UTC by yiraeChristineKim

Add documentation outlining the steps to transition from placementRule to placement

Ref: https://issues.redhat.com/browse/ACM-12698

2024-07-12 14:32 UTC, yiraeChristineKim commented
/cc @dhaiducek @mprahl

2024-07-12 17:27 UTC, gparvin commented on README.md
> +## Transition from PlacementRule to Placement
Can we call this something like: Distributing Policies to Managed Clusters

Then I think there are 3 sections, the Overview of what placement does, the Deprecated PlacementRule details, and then the Placement details.

I think we need to move the text found in another section of the README to the PlacementRules section.  That text is below:

```
The policies are applied to all managed clusters that are available, and have the environment set to dev. If policies need to be applied to another set of clusters, update the PlacementRule.spec.clusterSelector.matchExpressions section in the policies.

Note: As new clusters are added that fit the criteria previously mentioned, the policies are applied automatically.
```

2024-07-12 17:28 UTC, gparvin commented on README.md
> +### Prerequisite
I think this section should be called something like: Using PlacementRule to distribute policies (Deprectated)

2024-07-12 17:33 UTC, gparvin commented on README.md
> +      - {key: vendor, operator: In, values: ["OpenShift"]}
```suggestion
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
```

This matches what we documented previously.

2024-07-12 17:37 UTC, gparvin commented on README.md
> +## Convert PlacementRule to Placement
Maybe this should be 2 sections
1. One section that talks about doing the conversion
2. A second section that shows what a user does if they are new and just want to use Placement as a beginner

Maybe so that the conversion section is really brief - it could be the last section.

2024-07-12 17:37 UTC, gparvin commented on README.md
> +         - {key: vendor, operator: In, values: ["OpenShift"]}
Change this to match environment=dev like in the other comment.

2024-07-12 18:40 UTC, dhaiducek commented on README.md
> +## Transition from PlacementRule to Placement
Running Prettier on this file in VSCode ought to clean up/add the expected line breaks like this one:
```suggestion
## Transition from PlacementRule to Placement

```

2024-07-12 18:46 UTC, dhaiducek commented on README.md
> +## Transition from PlacementRule to Placement
I agree, though I think the "overview" can be embedded, like:
```
## Distributing Policies to Managed Clusters

...brief overview/intro about Policy -> PlacementBinding -> Placement and note about PlacementRule being deprecated...

### Using `Placement` with `Policies`

...stuff about Placement...

### Transitioning from `PlacementRule` (deprecated) to `Placement`

...stuff about migrating PlacementRule to Placement...
```

2024-07-12 18:47 UTC, dhaiducek commented on README.md
> +  name: binding-policy-comp-operator
(optional) I'd prefer this be more generic.
```suggestion
  name: binding-policy-example
```

2024-07-13 11:35 UTC, yiraeChristineKim commented on README.md
> +## Convert PlacementRule to Placement
For second section, should we link to https://open-cluster-management.io/concepts/placement/? Because it is already there. I think rewriting about placement is unnecessary.

2024-07-13 11:38 UTC, yiraeChristineKim commented on README.md
> +## Transition from PlacementRule to Placement
Do we have to write about placement and PlacementRule? because it is already in https://open-cluster-management.io/concepts/placement/.

2024-07-13 12:17 UTC, yiraeChristineKim commented on README.md
> +## Convert PlacementRule to Placement
I added!

2024-07-15 12:12 UTC, gparvin commented on README.md
> +The goal of converting from PlacementRule to Placement is to update your configuration from an older, deprecated format to a newer, more flexible one. This ensures alignment with current best practic
I think all of this can be deleted.  The new sections you have are the main content and the following section provides a good start on the Overview.

2024-07-15 12:18 UTC, gparvin commented on README.md
> +The policies are applied to all available managed clusters with the environment set to "dev." To apply the policies to a different set of clusters, update the PlacementRule.spec.clusterSelector.match
You copied this from a previous section, but this information is wrong.  Please delete the previous content containing these sentences.
```suggestion
Policies previously defined the `PlacementRule` and `PlacementBinding` resources along with the `Policy` configuring the policy to be distributed to all managed clusters with the label `environment` set to "dev." To apply your policies to managed clusters, use the information provided in this section instead since the `PlacementRule` and `PlacementBinding` resources are no longer being included with the policies in this repository.
```

2024-07-15 12:19 UTC, gparvin commented on README.md
> +As new clusters meeting the specified criteria are added, the policies will be applied to them automatically.
Probably should delete or move this sentence somewhere more appropriate.

2024-07-15 12:21 UTC, yiraeChristineKim commented on README.md
> +The policies are applied to all available managed clusters with the environment set to "dev." To apply the policies to a different set of clusters, update the PlacementRule.spec.clusterSelector.match
Because if "Policies previously defined..."  Should this part be inserted after "Prerequisite"?

2024-07-15 12:25 UTC, gparvin commented on README.md
> +- `PlacementBinding` and `PlacementRule`
It isn't clear why there's a Prerequisite section here.  I think you are wanting to show what needs to exist on the cluster prior to starting a procedure, but I think it's hard to understand without some more details.  I think it would make more sense to have a list of steps maybe.

Step 1: Make sure your clusters are organized as desired into ManagedCluster sets... see link 
Step 2: Make sure you have a ManagedClusterSetBinding for the namespace where you are authoring policies.  See link...
Step 3: Look for any PlacementBinding resources that point to a PlacementRule.  For each of those PlacementBindings, you need to continue with these steps.
Step 4: Change the PlacementBinding
Step 5: Change the PlacementRule

2024-07-16 20:42 UTC, dhaiducek commented on README.md
> +
I took what you had written and reflowed the content and pasted it back here (unfortunately the diff doesn't show the changes well 😞 ) since there were some smaller changes that I thought might be easier to show if I pasted the whole thing. The content you have is really good, but there seemed to be some duplication in there that I thought could be streamlined.

````suggestion
## Distributing Policies to Managed Clusters

Distributing a `Policy` to a managed cluster requires four parts, all of which must be in the same namespace:

- [Policy](https://open-cluster-management.io/concepts/policy/): A grouping mechanism for policy templates and is the smallest deployable unit on the hub cluster. Embedded Policy Templates are distributed to applicable managed clusters and acted upon by the appropriate policy controller.
- [PlacementBinding](https://open-cluster-management.io/concepts/policy/#placementbinding): Binds a `Placement` to a `Policy` or `PolicySet`.
- [Placement](https://open-cluster-management.io/concepts/placement/): Dynamically selects a set of `ManagedClusters` in one or multiple `ManagedClusterSet`s.
- [ManagedClusterSetBinding](https://open-cluster-management.io/concepts/managedclusterset/): Binds a `ManagedClusterSet` to a namespace, making this group of managed clusters available for selection by `Placement`.

When the `Policy` is bound to a `Placement` using a `PlacementBinding`, the `Policy` is distributed to the managed clusters and the `Policy` status will report on each cluster returned by the bound `Placement`.

### Using `Placement` with `Policies`

See the [Placement documentation](https://open-cluster-management.io/concepts/placement/) for additional details on selecting managed clusters using `Placement`.

To use `Placement` to distribute `Policies`, bind the `Policy` to the `Placement` using a `PlacementBinding`. All of the objects must be in the same namespace. View the following sample `Placement` and `PlacementBinding` bound to a `Policy` named `policy-example` in the namespace `example-ns`. The `Placement` selects managed clusters that have the label `environment: dev`:

```yaml
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-example
  namespace: example-ns
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
         - {key: environment, operator: In, values: ["dev"]}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-example
  namespace: example-ns
placementRef:
  name: placement-policy-example
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: policy-example
    kind: Policy
    apiGroup: policy.open-cluster-management.io
```

### Transitioning from `PlacementRule`(deprecated) to `Placement`

`PlacementRule` had unrestricted access to selecting managed clusters. However, `Placement` requires binding managed clusters to the `Policy` namespace in order for `Policies` to be distributed to those managed clusters, bringing an additional layer of control to system administrators. View the following steps on migrating from `PlacementRule` to `Placement`:

1. The desired managed clusters must be contained in a `ManagedClusterSet`. See the [ManagedClusterSet documentation](https://open-cluster-management.io/concepts/managedclusterset/) to read more, including the default sets that are available that include all managed clusters that would replicate `PlacementRule` behavior.

2. Create a `ManagedClusterSetBinding` to bind the `ManagedClusterSet` to the namespace where you are authoring policies. See the [ManagedClusterSet documentation](https://open-cluster-management.io/concepts/managedclusterset/).

3. Create the `Placement` manifest to replace the `PlacementRule`. To do this, take the selector `spec.clusterSelector` from the `PlacementRule` and put it into `spec.predicates.requiredClusterSelector.labelSelector`. For example, to select managed clusters with the label `environment: dev`:
   ```yaml
   apiVersion: cluster.open-cluster-management.io/v1beta1
   kind: Placement
   metadata:
     name: placement-policy-example
     namespace: example-ns // Ensure this namespace matches the ManagedClusterSetBinding
   spec:
     predicates:
     - requiredClusterSelector:
         labelSelector:
           matchExpressions: // From PlacementRule
           - {key: environment, operator: In, values: ["dev"]}
   ```

   See the [Placement documentation](https://open-cluster-management.io/concepts/placement/) for additional details on selecting managed clusters using `Placement`.

4. Identify any `PlacementBinding` resources that reference a `PlacementRule`. Update the `PlacementBinding` to reference the new `Placement`:
   - Change the `placementRef.kind` to `Placement`
   - Update the `placementRef.apiGroup` to `cluster.open-cluster-management.io` to reflect the `Placement`'s API version

   View the following sample `PlacementBinding` that references a `Placement`:

   ```yaml
   apiVersion: policy.open-cluster-management.io/v1
   kind: PlacementBinding
   metadata:
     name: binding-policy-example
   placementRef:
     apiGroup: cluster.open-cluster-management.io // Set to cluster.open-cluster-management.io
     kind: Placement                              // Set to Placement
     name: placement-policy-example
   subjects:
     - name: policy-example
       kind: Policy
       apiGroup: policy.open-cluster-management.io
   ```
````

2024-07-18 13:39 UTC, dhaiducek requested changes
Looking good! I have one comment about the sections.

Please also run the code through a linter to reflow any long lines to match the rest of the file.

2024-07-18 13:39 UTC, dhaiducek commented on README.md
> +To use `Placement` to distribute `Policies`, bind the `Policy` to the `Placement` using a `PlacementBinding`. All of the objects must be in the same namespace. View the following sample `Placement` a
These sections can be combined into a single heading.
I've also removed "now" (which is unclear since that could be any time it's being read) and "recommend" since it's a requirement and not optional given the deprecation.

```suggestion
### Using `Placement` with `Policies`

See the [Placement documentation](https://open-cluster-management.io/concepts/placement/) for additional details on selecting managed clusters using `Placement`.

- **NOTE:** `PlacementRule` is **deprecated**. See the [migration section](#transitioning-from-placementruledeprecated-to-placement) for detail on migrating to `Placement`.

To use `Placement` to distribute `Policies`, bind the `Policy` to the `Placement` using a `PlacementBinding`. All of the objects must be in the same namespace. View the following sample `Placement` and `PlacementBinding` bound to a `Policy` named `policy-example` in the namespace `example-ns`. The `Placement` selects managed clusters that have the label `environment: dev`:
```

2024-07-18 20:37 UTC, dhaiducek commented on README.md
> +- [Policy](https://open-cluster-management.io/concepts/policy/) is a grouping mechanism for Policy Templates and is the smallest deployable unit on the hub cluster. Embedded Policy Templates are dist
Lines such as this one are still too long--would you please run Prettier (or something similar) in VSCode to wrap them to match the rest of the file?

2024-07-18 20:47 UTC, yiraeChristineKim commented on README.md
> +- [Policy](https://open-cluster-management.io/concepts/policy/) is a grouping mechanism for Policy Templates and is the smallest deployable unit on the hub cluster. Embedded Policy Templates are dist
I used both no change
![Screenshot 2024-07-18 at 4 47 06 PM](https://github.com/user-attachments/assets/20277514-b476-4a8d-a750-dd9f5ccb98c3)

2024-07-18 20:48 UTC, yiraeChristineKim commented on README.md
> +- [Policy](https://open-cluster-management.io/concepts/policy/) is a grouping mechanism for Policy Templates and is the smallest deployable unit on the hub cluster. Embedded Policy Templates are dist
Where do you want to change?

2024-07-18 21:02 UTC, dhaiducek commented on README.md
> +- [Policy](https://open-cluster-management.io/concepts/policy/) is a grouping mechanism for Policy Templates and is the smallest deployable unit on the hub cluster. Embedded Policy Templates are dist
Oh! You _might_ need to set the "Prettier: Print Width" to 100 (I think I usually have it set to 120, but it looks like this file was originally wrapped at 100)

![image](https://github.com/user-attachments/assets/2ee63168-81e5-4787-abd5-fb2c17109dfa)

2024-07-19 14:13 UTC, yiraeChristineKim commented on README.md
> +- [Policy](https://open-cluster-management.io/concepts/policy/) is a grouping mechanism for Policy Templates and is the smallest deployable unit on the hub cluster. Embedded Policy Templates are dist
<img width="482" alt="Screenshot 2024-07-19 at 10 13 35 AM" src="https://github.com/user-attachments/assets/108705da-c3cb-4cde-9914-533022b0d08e">
Umm nothing changed

2024-07-19 14:35 UTC, dhaiducek commented on README.md
> +- [Policy](https://open-cluster-management.io/concepts/policy/) is a grouping mechanism for Policy Templates and is the smallest deployable unit on the hub cluster. Embedded Policy Templates are dist
Oh, I think I know. Try setting "Prettier: Prose Wrap" to "always":
![image](https://github.com/user-attachments/assets/b7219e80-1d4d-4f70-87c6-1c6867ddad28)

2024-07-19 18:08 UTC, yiraeChristineKim commented on README.md
> +- [Policy](https://open-cluster-management.io/concepts/policy/) is a grouping mechanism for Policy Templates and is the smallest deployable unit on the hub cluster. Embedded Policy Templates are dist
OH~~~ changed a lot

2024-07-24 18:29 UTC, dhaiducek commented on README.md
> +additional details on selecting managed clusters using `Placement`.
(Optional) Indent to flow with bullet 3.
```suggestion
   See the [Placement documentation](https://open-cluster-management.io/concepts/placement/) for
   additional details on selecting managed clusters using `Placement`.
```

2024-07-25 14:16 UTC, dhaiducek requested changes

2024-07-25 14:16 UTC, dhaiducek commented on README.md
> +  additional details on selecting managed clusters using `Placement`.
This should have stayed over to the left--it's the other paragraph that needed to move over.

2024-07-25 14:32 UTC, dhaiducek approved these changes
LGTM! Thanks, @yiraeChristineKim!

2024-07-25 14:37 UTC, merged