Clarify pull request usage in README
open-cluster-management-io/policy-collection pull request #494
Opened 2024-07-17 17:05 UTC by tavaresrodrigo

This pull request addresses an issue in the policy-collection README where the usage of pull requests may be confusing.

The current text suggests using a pull request to pull changes, which is not accurate. A pull request should be used to propose merging changes.

**Changes Made:**
- Updated the sentence from:
  ```
  Fork this repository and use the forked version as the target to run the sync against. This is to
  avoid unintended changes to be applied to your cluster automatically. To get latest policies from
  the `policy-collection` repository, you can pull the latest changes from `policy-collection` to your
  own repository through a pull request. Any further changes to your repository are automatically be
  applied to your cluster.
  ```
  to:
  ```
  Fork this repository and use the forked version as the target to run the sync. This avoids unintended changes to your cluster. 
  To get the latest policies from the `policy-collection` repository, pull the latest changes from `policy-collection` and then create a pull request to merge these changes into your forked repository. Any further changes to your repository will be applied to your cluster automatically.
  ```

This change ensures that the instructions are clear and technically accurate, helping users understand the correct use of pull requests.

2024-07-17 17:34 UTC, tavaresrodrigo commented
Signed-off-by: Rodrigo Tavares <[rotavares@redhat.com](mailto:rotavares@redhat.com)>

2024-07-17 17:38 UTC, dhaiducek commented
@tavaresrodrigo Thanks for the PR! For the DCO signoff, since there's only one commit you can run these commands to add the signoff:

```bash
git commit --amend --signoff --no-edit
git push --force
```

2024-07-17 17:41 UTC, dhaiducek requested changes
Thanks for the update! I think the wording looks good--just needs some linting and it'll be good to go!

2024-07-17 17:41 UTC, dhaiducek commented on README.md
> +To get the latest policies from the `policy-collection` repository, pull the latest changes from `policy-collection` and then create a pull request to merge these changes into your forked repository.
Reflow to match the Markdown formatting:

```suggestion
Fork this repository and use the forked version as the target to run the sync. This avoids
unintended changes to your cluster. To get the latest policies from the `policy-collection`
repository, pull the latest changes from `policy-collection` and then create a pull request to merge
these changes into your forked repository. Any further changes to your repository will be applied to
your cluster automatically.
```

2024-07-17 17:50 UTC, dhaiducek commented
We prefer to minimize the number of commits--would you please squash these commits into a single commit? (Let me know if any guidance is needed on squashing.) After that, it should be good to merge.

2024-07-17 18:00 UTC, tavaresrodrigo commented
Thanks for the helpful guidance @dhaiducek ! I have squashed all commits.

2024-07-18 13:30 UTC, dhaiducek approved these changes
Thanks for the update, @tavaresrodrigo!

2024-07-18 13:35 UTC, merged