add additional checks for compliace operator scans
open-cluster-management-io/policy-collection pull request #55
Opened 2020-12-08 22:58 UTC by ycao56

1. update compliance operator to watch for openshift-compliance ns
2. use configuration policy to create scansettingbindings
3. add additional policy templates to 
   1. check if the scan is complete
   2. if there is any remediation required

2020-12-09 07:27 UTC, JAORMX requested changes

2020-12-09 07:27 UTC, JAORMX commented on community/CA-Security-Assessment-and-Authorization/policy-compliance-operator-install-upstream.yaml
> -                      policy.open-cluster-management.io/isClusterNamespace: "true"
Why was this removed? Don't we have this in RHACM nowadays?

2020-12-09 07:27 UTC, JAORMX commented on community/CM-Configuration-Management/policy-compliance-operator-e8-scan.yaml
> +        kind: ConfigurationPolicy
The whole integration work was to have the compliance-operator issue events directly to RHACM. This removes that capability and relies on another controller which is not what this policy was meant to do.

2020-12-15 15:56 UTC, ycao56 commented on community/CA-Security-Assessment-and-Authorization/policy-compliance-operator-install-upstream.yaml
> -                      policy.open-cluster-management.io/isClusterNamespace: "true"
discussed offline that we are going to switch to use configuration policy to create ScanSettingBinding

2020-12-15 15:56 UTC, ycao56 commented on community/CM-Configuration-Management/policy-compliance-operator-e8-scan.yaml
> +        kind: ConfigurationPolicy
discussed offline that we are going to switch to use configuration policy to create ScanSettingBinding

2020-12-15 15:57 UTC, ycao56 commented on community/CM-Configuration-Management/policy-compliance-operator-e8-scan.yaml
> +          name: compliance-suite-e8-results
@JAORMX switched to check for `ComplianceCheckResult` CRs with label `                 compliance.openshift.io/check-status: FAIL`

2020-12-15 16:24 UTC, gparvin approved these changes
Approving changes discussed in call with compliance team.

2020-12-15 16:27 UTC, merged