Added policy-integrity-shield.yaml
open-cluster-management-io/policy-collection pull request #60
Opened 2020-12-10 15:59 UTC by yuji-watanabe-jp

@ycao56 this is the policy to enable Integrity Shield on managed clusters. We have tested on our test clusters. Please review and merge. Thanks.

2020-12-10 22:44 UTC, ycao56 commented on community/CM-Configuration-Management/policy-integrity-shield.yaml
> +  remediationAction: enforce
update it to `inform` as we don't want to surprise users

2020-12-10 22:45 UTC, ycao56 commented on community/CM-Configuration-Management/policy-integrity-shield.yaml
> +          namespaceSelector:
remove `namespaceSelector` as the embedded CR is a cluster scope resource

2020-12-10 22:46 UTC, ycao56 commented on community/CM-Configuration-Management/policy-integrity-shield.yaml
> +          namespaceSelector:
remove `namespaceSelector` as namespace has been already specified in embedded object

2020-12-10 22:46 UTC, ycao56 commented on community/CM-Configuration-Management/policy-integrity-shield.yaml
> +            include: ["integrity-shield-operator-system"]
can just specify the namespace in `integrity-shield-server`

2020-12-11 13:53 UTC, ycao56 approved these changes
LGTM. Will merge after @dockerymick reviewed the text

2020-12-14 03:22 UTC, dockerymick requested changes

2020-12-14 03:22 UTC, dockerymick commented on community/README.md
> +[Integrity Shield](./CM-Configuration-Management/policy-integrity-shield)| Use the Integrity Shield to protect integrity of Kubenernetes resources in a cluster (e.g. OpenShift). | See the [Integrity
The link for Integrity Shield is broken. i received a 404 Error when I selected it.

2020-12-14 04:34 UTC, gajananan commented on community/README.md
> +[Integrity Shield](./CM-Configuration-Management/policy-integrity-shield)| Use the Integrity Shield to protect integrity of Kubenernetes resources in a cluster (e.g. OpenShift). | See the [Integrity
@dockerymick I fixed the link for Integrity Shield,  please check. Thank you.

2020-12-14 12:45 UTC, dockerymick commented on community/README.md
> +[Integrity Shield](./CM-Configuration-Management/policy-integrity-shield.yaml)| Use the Integrity Shield to protect integrity of Kubenernetes resources in a cluster (e.g. OpenShift). | See the [Integ
Update the first sentence to read: "Use the Integrity Shield to protect **the** integrity of Kubenernetes..."

2020-12-14 12:46 UTC, dockerymick approved these changes
Please address my comment before merging. Other than that, the changes look good !

2020-12-14 12:51 UTC, gajananan commented on community/README.md
> +[Integrity Shield](./CM-Configuration-Management/policy-integrity-shield.yaml)| Use the Integrity Shield to protect integrity of Kubenernetes resources in a cluster (e.g. OpenShift). | See the [Integ
Thank you, I have addressed your comments. @dockerymick

2020-12-14 13:11 UTC, dockerymick commented on community/README.md
> +[Integrity Shield](./CM-Configuration-Management/policy-integrity-shield.yaml)| Use the Integrity Shield to protect integrity of Kubenernetes resources in a cluster (e.g. OpenShift). | See the [Integ
Thank you ! @gajananan

2020-12-14 17:56 UTC, merged